name: Combined Proxy + Config Bots

on:
  schedule:
    - cron: '*/5 * * * *'
  workflow_dispatch:
# Keep-alive update for cron
jobs:
  run-config-bot:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'

      - name: Run Config Bot Text Version
        run: php configbot_text_based.php
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          CHANNEL_ID: ${{ secrets.CHANNEL_ID }}
